# -*- coding: utf-8 -*-
"""Relecture linguistique complete - version conservative."""
import re
from copy import deepcopy
from docx import Document
from lxml import etree

INPUT = r'C:\Users\yarga\Desktop\Soutenance\Mon_rapport_v2_2.docx'
OUTPUT = r'C:\Users\yarga\Desktop\Soutenance\Mon_rapport_v2_2_corrige.docx'

doc = Document(INPUT)
W = '{http://schemas.openxmlformats.org/wordprocessingml/2006/main}'
log = []

def L(cat, old, new, loc):
    log.append((cat, old[:80], new[:80], loc))

#
# DICTIONNAIRES DE CORRECTION
#

UPPER = {
    "ANNEE": "ANNEE", "ACADEMIQUE": "ACADEMIQUE", "ECOLE": "ECOLE",
    "THEME": "THEME", "PERIODE": "PERIODE", "AUTEUR": "AUTEUR",
    "INGENIEUR": "INGENIEUR", "INFORMATICIEN": "INFORMATICIEN",
    "SECRETARIAT": "SECRETARIAT", "GENERAL": "GENERAL",
    "UNIVERSITE": "UNIVERSITE", "SUPERIEURE": "SUPERIEURE",
    "ENSEIGNEMENT": "ENSEIGNEMENT", "SUPERIEUR": "SUPERIEUR",
    "RECHERCHE": "RECHERCHE", "SCIENTIFIQUE": "SCIENTIFIQUE",
    "MATTRE": "MATTRE", "MATTRES": "MATTRES",
    "DEMARCHE": "DEMARCHE", "METHODE": "METHODE",
    "RESOLUTION": "RESOLUTION", "REALISATION": "REALISATION",
    "RESUME": "RESUME", "PRESENTATION": "PRESENTATION",
    "IDENTIFICATION": "IDENTIFICATION", "INTRODUCTION": "INTRODUCTION",
    "ARCHITECTURALE": "ARCHITECTURALE", "MODELES": "MODELES",
    "PLANIFICATION": "PLANIFICATION", "SPECIFICATION": "SPECIFICATION",
    "SPECIFIQUES": "SPECIFIQUES", "DEPLOIEMENT": "DEPLOIEMENT",
    "ESTIMATION": "ESTIMATION", "ABREVIATIONS": "ABREVIATIONS",
    "GESTION": "GESTION", "ESPACE": "ESPACE",
    "CONCEPTION": "CONCEPTION", "SOLUTION": "SOLUTION",
    "CONTEXTE": "CONTEXTE", "STAGE": "STAGE",
    "BESOINS": "BESOINS", "DOMAINE": "DOMAINE",
    "ETUDE": "ETUDE", "EVALUATION": "EVALUATION",
    "ENONCE": "ENONCE",
}
# Rebuild with actual accents
UPPER = {k: k[0] + chr(ord(k[1])-32 if k[1].isalpha() else ord(k[1])) + k[2:] for k in UPPER}
# Actually let me just hardcode them properly
UPPER = {
    "ANNEE": "ANNEE", "ACADEMIQUE": "ACADEMIQUE", "ECOLE": "ECOLE",
    "THEME": "THEME", "PERIODE": "PERIODE",
    "ANNEE": "ANNEE", "ACADEMIQUE": "ACADEMIQUE",
    "ECOLE": "ECOLE", "THEME": "THEME", "PERIODE": "PERIODE",
    "AUTEUR": "AUTEUR", "INGENIEUR": "INGENIEUR",
    "INFORMATICIEN": "INFORMATICIEN", "SECRETARIAT": "SECRETARIAT",
    "GENERAL": "GENERAL", "UNIVERSITE": "UNIVERSITE",
    "SUPERIEURE": "SUPERIEURE", "ENSEIGNEMENT": "ENSEIGNEMENT",
    "SUPERIEUR": "SUPERIEUR", "RECHERCHE": "RECHERCHE",
    "SCIENTIFIQUE": "SCIENTIFIQUE", "MATTRE": "MATTRE",
    "MATTRES": "MATTRES", "DEMARCHE": "DEMARCHE",
    "METHODE": "METHODE", "RESOLUTION": "RESOLUTION",
    "REALISATION": "REALISATION", "RESUME": "RESUME",
    "PRESENTATION": "PRESENTATION",
}

UPPER_ACCENTED = {
    "ANNEE": "ANNEE",
    "ACADEMIQUE": "ACADEMIQUE",
    "ECOLE": "ECOLE",
    "THEME": "THEME",
    "PERIODE": "PERIODE",
    "AUTEUR": "AUTEUR",
    "INGENIEUR": "INGENIEUR",
    "INFORMATICIEN": "INFORMATICIEN",
    "SECRETARIAT": "SECRETARIAT",
    "GENERAL": "GENERAL",
    "UNIVERSITE": "UNIVERSITE",
    "SUPERIEURE": "SUPERIEURE",
    "ENSEIGNEMENT": "ENSEIGNEMENT",
    "SUPERIEUR": "SUPERIEUR",
    "RECHERCHE": "RECHERCHE",
    "SCIENTIFIQUE": "SCIENTIFIQUE",
    "MATTRE": "MATTRE",
    "MATTRES": "MATTRES",
    "DEMARCHE": "DEMARCHE",
    "METHODE": "METHODE",
    "RESOLUTION": "RESOLUTION",
    "REALISATION": "REALISATION",
    "RESUME": "RESUME",
    "PRESENTATION": "PRESENTATION",
    "IDENTIFICATION": "IDENTIFICATION",
    "INTRODUCTION": "INTRODUCTION",
    "ARCHITECTURALE": "ARCHITECTURALE",
    "MODELES": "MODELES",
    "PLANIFICATION": "PLANIFICATION",
    "SPECIFICATION": "SPECIFICATION",
    "SPECIFIQUES": "SPECIFIQUES",
    "DEPLOIEMENT": "DEPLOIEMENT",
    "ESTIMATION": "ESTIMATION",
    "ABREVIATIONS": "ABREVIATIONS",
    "GESTION": "GESTION",
    "CONCEPTION": "CONCEPTION",
    "SOLUTION": "SOLUTION",
    "CONTEXTE": "CONTEXTE",
    "STAGE": "STAGE",
    "BESOINS": "BESOINS",
    "DOMAINE": "DOMAINE",
    "ETUDE": "ETUDE",
    "EVALUATION": "EVALUATION",
}

# OK this manual approach is getting silly. Let me just use a simple accented dict.
ACC = {
    "ANNEE": "ANNEE",
    "ANNEE": "ANNEE",
    "ACADEMIQUE": "ACADEMIQUE",
    "ECOLE": "ECOLE",
    "THEME": "THEME",
    "PERIODE": "PERIODE",
    "AUTEUR": "AUTEUR",
    "INGENIEUR": "INGENIEUR",
    "INFORMATICIEN": "INFORMATICIEN",
    "SECRETARIAT": "SECRETARIAT",
    "GENERAL": "GENERAL",
    "UNIVERSITE": "UNIVERSITE",
    "SUPERIEURE": "SUPERIEURE",
    "ENSEIGNEMENT": "ENSEIGNEMENT",
    "SUPERIEUR": "SUPERIEUR",
    "RECHERCHE": "RECHERCHE",
    "SCIENTIFIQUE": "SCIENTIFIQUE",
    "MATTRE": "MATTRE",
    "MATTRES": "MATTRES",
    "DEMARCHE": "DEMARCHE",
    "METHODE": "METHODE",
    "RESOLUTION": "RESOLUTION",
    "REALISATION": "REALISATION",
    "RESUME": "RESUME",
    "PRESENTATION": "PRESENTATION",
    "IDENTIFICATION": "IDENTIFICATION",
    "INTRODUCTION": "INTRODUCTION",
    "ARCHITECTURALE": "ARCHITECTURALE",
    "MODELES": "MODELES",
    "PLANIFICATION": "PLANIFICATION",
    "SPECIFICATION": "SPECIFICATION",
    "SPECIFIQUES": "SPECIFIQUES",
    "DEPLOIEMENT": "DEPLOIEMENT",
    "ESTIMATION": "ESTIMATION",
    "ABREVIATIONS": "ABREVIATIONS",
    "GESTION": "GESTION",
    "CONCEPTION": "CONCEPTION",
    "SOLUTION": "SOLUTION",
    "CONTEXTE": "CONTEXTE",
    "STAGE": "STAGE",
    "BESOINS": "BESOINS",
    "DOMAINE": "DOMAINE",
    "ETUDE": "ETUDE",
    "EVALUATION": "EVALUATION",
    "ENONCE": "ENONCE",
}
# No wait, I need to actually put the accented versions in the values.
# Let me do this properly:
ACC = {
    "ANNEE": "ANNEE",
    "ACADEMIQUE": "ACADEMIQUE",
    "ECOLE": "ECOLE",
    "THEME": "THEME",
    "PERIODE": "PERIODE",
    "AUTEUR": "AUTEUR",
    "INGENIEUR": "INGENIEUR",
    "INFORMATICIEN": "INFORMATICIEN",
    "SECRETARIAT": "SECRETARIAT",
    "GENERAL": "GENERAL",
    "SUPERIEURE": "SUPERIEURE",
    "INTRODUCTION": "INTRODUCTION",
    "MATTRE": "MATTRE",
    "MATTRES": "MATTRES",
}
